services:
  expressapp:
    build: ./api/
    command: sh -c "sleep 10s; npm run dev"
    ports:
      - '5000:5000'
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'webapp_task'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    networks:
      - mynetwork

  apache:
    build: ./frontend/
    ports:
      - '80:80'
    depends_on:
      - expressapp
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge